### PR TITLE
Build with webpack

### PR DESCRIPTION
**Pull request by nnarhinen**
@blacktrash Please take a look at this. Uses webpack to bundle the files, also creates the hls.js from source.

### CODE REVIEW

**Comment by blacktrash** [comment]
Nice.
However, I get errors. I first presumed that's because of load order, from top to bottom in the minified flowplayer.hlsjs.min.js:
- license
- flowplayer.hlsjs.js
- hls.js

and not:
- license
- hls.js
- flowplayer.hlsjs.js

But now saw that the hls.js which is left in the dist folder differs a lot from the actual release - will check whether it's just indentation.

Will play around with it a bit.

+1 for ensuring bash, -1 for useless use of cat ;-)

**Comment by nnarhinen** [comment]
Can you paste the errors

**Comment by blacktrash** [comment]
With `hlsjs.debug: true`:
'[error] > error while initializing DemuxerWorker, fallback on DemuxerInline'
Not sure whether this points to something deeper.

**Comment by blacktrash** [comment]
The hls.js file in the dist folder does not feature `Hls.isSupported()`. That could be worked around in the plugin because it's a wrapper around `MediaSource.isTypeSupported()`, but again I'm insecure what's going on.
Loading both unminified can be useful for debugging.

**Comment by nnarhinen** [comment]
Ok I'll check what's going on, tomorrow.

**Comment by blacktrash** [comment]
No worries. webpacked flowplayer.hlsjs.min.js is 4kb smaller than the current release, so some stuff is definitely missing, I'm just not sure how vital it is.

**Comment by nnarhinen** [comment]
The debug builds now use the official distribution (see dailymotion/hls.js#244 )

The minified build worked for me already before the latest change. Do you still see problems with it?

**Comment by blacktrash** [comment]
@nnarhinen - I'll play around with it.
otoh, the minified production plugin, would probably use a release as well - or even more so.

**Comment by blacktrash** [comment]
Let's try it. Allows us to target an intermediate hls.js commit for production if needed/desired.

**Pull request merged**
