### PR TITLE
if master manifest has name, show it as label

### PR DESCRIPTION
**Pull request by mysamimi**
my change is 
....
if (level.name) {
label = level.name;
} else if (level.width && level.height) {
...
VS code beautify another lines :)

### CODE REVIEW

**Comment by bbbo** [comment]
@nnarhinen perhaps an option for hlsjs-lite as well?

**Comment by mysamimi** [comment]
hlsjs already extract NAME from master manifest, but flow player-hlsjs ignore it.
this coed use master manifest label.

**Comment by nnarhinen** [comment]
We will not maintain this plugin anymore. You should start using [the internal hlsjs engine of flowplayer](https://flowplayer.com/docs/player/setup#hlsjs-lite).

If you still want this functionality, you should port your changes to that repository. Also FYI this pull request contains too much unrelated whitespace changes to get merged.

**Comment by mysamimi** [comment]
tnx Niklas

**Pull request closed without merging**
