### PR TITLE
Add commonjs support

### PR DESCRIPTION
**Pull request by nnarhinen**
This allows this plugin to be used in a browserify / webpack environment
with a commonjs loader

Usage:

```js
var flowplayer = require('flowplayer');
require('flowplayer-hlsjs'); // Plugin injects itself to flowplayer

flowplayer('#container', {
  clip: {
    sources: [{
      type: 'application/x-mpegurl',
      src: '//stream.flowplayer.org/bauhaus.m3u8'
    }]
  }
});
```

### CODE REVIEW

**Comment by nnarhinen** [comment]
@blacktrash In order to do this I had to upgrade hls.js. You should definitely cross-check it will still work.

I looked at the commit changes and they were mostly build related so I guess it should be fine. Could you also please check that the plugin actually still works in a "normal" environment. I only tested in a commonjs environment.

**Comment by blacktrash** [comment]
@nnarhinen - I'll look at this some time next week, I'm not familiar with this kind of workflow.
What you could do in the mean-time is ask @mangui whether this would be ok licensing-wise. afaics we would have no license header or pointer for hls.js's Apache license anymore. thx.

**Comment by nnarhinen** [comment]
It does not differ. In the bundle we distribute (the flowplayer.hls.min.js from our cdn) we have the same licenses and headers as before, that is not affected.

With this pull request we make it possible to install flowplayer-hlsjs with npm and allow them bundle flowplayer *and* flowplayer-hlsjs to their own application. They are used as libraries (licensing-wise). flowplayer-hlsjs just pulls in a dependency: hls.js. So it is actually the responsibility of the implementor to list all their dependencies (including hls.js which is a dependency of dependency) with their licenses (if t he licenses need that).

**Comment by blacktrash** [comment]
Yup, very cool. I just had to familiarize myself a bit with it.
Thank you.

**Pull request merged**
